### ISSUE TITLE
DBUnexpectedError

### ISSUE THREAD

**Issue by codecat** [HydraWiki/SpriteSheet#2]
I get this error when I try saving a spritesheet, both on 1.2.0 and 1.1.5 on Mediawiki 1.31.0. The database I'm using for this setup is MySQL, if it matters.
```
{"error":{"code":"internal_api_error_DBUnexpectedError","info":"[f687197b90af7b7656ca74c4] Exception caught: Wikimedia\\Rdbms\\Database::begin: Implicit transaction already active (from Wikimedia\\Rdbms\\Database::query (SpriteSheet::load))."}}
```

**Comment by Alexia** [comment]
Sorry, I forgot to update this ticket after the fix was put out.  Version 1.3.0 took care of this.

https://github.com/HydraWiki/SpriteSheet/releases/tag/v1.3.0
